// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateEventInput struct {
	Destination string         `json:"destination"`
	Payload     map[string]any `json:"payload"`
	Headers     map[string]any `json:"headers,omitempty"`
	MaxAttempts *int           `json:"maxAttempts,omitempty"`
}

type DeliveryAttempt struct {
	ID            string    `json:"id"`
	EventID       string    `json:"eventId"`
	StatusCode    *int      `json:"statusCode,omitempty"`
	ResponseBody  *string   `json:"responseBody,omitempty"`
	Error         *string   `json:"error,omitempty"`
	DurationMs    int       `json:"durationMs"`
	AttemptNumber int       `json:"attemptNumber"`
	AttemptedAt   time.Time `json:"attemptedAt"`
}

type Event struct {
	ID               string            `json:"id"`
	IdempotencyKey   string            `json:"idempotencyKey"`
	Destination      string            `json:"destination"`
	Payload          map[string]any    `json:"payload"`
	Headers          map[string]any    `json:"headers,omitempty"`
	Status           EventStatus       `json:"status"`
	Attempts         int               `json:"attempts"`
	MaxAttempts      int               `json:"maxAttempts"`
	NextAttemptAt    *time.Time        `json:"nextAttemptAt,omitempty"`
	DeliveredAt      *time.Time        `json:"deliveredAt,omitempty"`
	CreatedAt        time.Time         `json:"createdAt"`
	UpdatedAt        time.Time         `json:"updatedAt"`
	DeliveryAttempts []DeliveryAttempt `json:"deliveryAttempts"`
}

type EventConnection struct {
	Edges      []EventEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type EventEdge struct {
	Node   *Event `json:"node"`
	Cursor string `json:"cursor"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type QueueStats struct {
	Queued     int `json:"queued"`
	Delivering int `json:"delivering"`
	Delivered  int `json:"delivered"`
	Failed     int `json:"failed"`
	Dead       int `json:"dead"`
	Pending    int `json:"pending"`
	Processing int `json:"processing"`
	Delayed    int `json:"delayed"`
}

type EventStatus string

const (
	EventStatusQueued     EventStatus = "QUEUED"
	EventStatusDelivering EventStatus = "DELIVERING"
	EventStatusDelivered  EventStatus = "DELIVERED"
	EventStatusFailed     EventStatus = "FAILED"
	EventStatusDead       EventStatus = "DEAD"
)

var AllEventStatus = []EventStatus{
	EventStatusQueued,
	EventStatusDelivering,
	EventStatusDelivered,
	EventStatusFailed,
	EventStatusDead,
}

func (e EventStatus) IsValid() bool {
	switch e {
	case EventStatusQueued, EventStatusDelivering, EventStatusDelivered, EventStatusFailed, EventStatusDead:
		return true
	}
	return false
}

func (e EventStatus) String() string {
	return string(e)
}

func (e *EventStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventStatus", str)
	}
	return nil
}

func (e EventStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
