// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type BatchRetryError struct {
	EventID string `json:"eventId"`
	Error   string `json:"error"`
}

type BatchRetryResult struct {
	Succeeded      []Event           `json:"succeeded"`
	Failed         []BatchRetryError `json:"failed"`
	TotalRequested int               `json:"totalRequested"`
	TotalSucceeded int               `json:"totalSucceeded"`
}

type CreateEndpointInput struct {
	URL              string         `json:"url"`
	Description      *string        `json:"description,omitempty"`
	EventTypes       []string       `json:"eventTypes"`
	Filter           map[string]any `json:"filter,omitempty"`
	Transformation   *string        `json:"transformation,omitempty"`
	MaxRetries       *int           `json:"maxRetries,omitempty"`
	RetryBackoffMs   *int           `json:"retryBackoffMs,omitempty"`
	RetryBackoffMax  *int           `json:"retryBackoffMax,omitempty"`
	RetryBackoffMult *float64       `json:"retryBackoffMult,omitempty"`
	TimeoutMs        *int           `json:"timeoutMs,omitempty"`
	RateLimitPerSec  *int           `json:"rateLimitPerSec,omitempty"`
	CircuitThreshold *int           `json:"circuitThreshold,omitempty"`
	CircuitResetMs   *int           `json:"circuitResetMs,omitempty"`
	CustomHeaders    map[string]any `json:"customHeaders,omitempty"`
}

type CreateEventInput struct {
	Destination string         `json:"destination"`
	Payload     map[string]any `json:"payload"`
	Headers     map[string]any `json:"headers,omitempty"`
	MaxAttempts *int           `json:"maxAttempts,omitempty"`
}

type CreateEventTypeInput struct {
	Name          string         `json:"name"`
	Description   *string        `json:"description,omitempty"`
	Schema        map[string]any `json:"schema,omitempty"`
	SchemaVersion *string        `json:"schemaVersion,omitempty"`
}

type DeliveryAttempt struct {
	ID            string    `json:"id"`
	EventID       string    `json:"eventId"`
	StatusCode    *int      `json:"statusCode,omitempty"`
	ResponseBody  *string   `json:"responseBody,omitempty"`
	Error         *string   `json:"error,omitempty"`
	DurationMs    int       `json:"durationMs"`
	AttemptNumber int       `json:"attemptNumber"`
	AttemptedAt   time.Time `json:"attemptedAt"`
}

type Endpoint struct {
	ID               string         `json:"id"`
	ClientID         string         `json:"clientId"`
	URL              string         `json:"url"`
	Description      *string        `json:"description,omitempty"`
	EventTypes       []string       `json:"eventTypes"`
	Status           EndpointStatus `json:"status"`
	Filter           map[string]any `json:"filter,omitempty"`
	Transformation   *string        `json:"transformation,omitempty"`
	MaxRetries       int            `json:"maxRetries"`
	RetryBackoffMs   int            `json:"retryBackoffMs"`
	RetryBackoffMax  int            `json:"retryBackoffMax"`
	RetryBackoffMult float64        `json:"retryBackoffMult"`
	TimeoutMs        int            `json:"timeoutMs"`
	RateLimitPerSec  int            `json:"rateLimitPerSec"`
	CircuitThreshold int            `json:"circuitThreshold"`
	CircuitResetMs   int            `json:"circuitResetMs"`
	CustomHeaders    map[string]any `json:"customHeaders,omitempty"`
	HasCustomSecret  bool           `json:"hasCustomSecret"`
	SecretRotatedAt  *time.Time     `json:"secretRotatedAt,omitempty"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	Stats            *EndpointStats `json:"stats"`
	RecentEvents     []Event        `json:"recentEvents"`
}

type EndpointConnection struct {
	Edges      []EndpointEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type EndpointEdge struct {
	Node   *Endpoint `json:"node"`
	Cursor string    `json:"cursor"`
}

type EndpointSecretRotation struct {
	Endpoint  *Endpoint `json:"endpoint"`
	NewSecret string    `json:"newSecret"`
}

type EndpointStats struct {
	TotalEvents  int     `json:"totalEvents"`
	Delivered    int     `json:"delivered"`
	Failed       int     `json:"failed"`
	Pending      int     `json:"pending"`
	SuccessRate  float64 `json:"successRate"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
}

type Event struct {
	ID               string            `json:"id"`
	IdempotencyKey   string            `json:"idempotencyKey"`
	ClientID         *string           `json:"clientId,omitempty"`
	EventType        *string           `json:"eventType,omitempty"`
	EndpointID       *string           `json:"endpointId,omitempty"`
	Destination      string            `json:"destination"`
	Payload          map[string]any    `json:"payload"`
	Headers          map[string]any    `json:"headers,omitempty"`
	Status           EventStatus       `json:"status"`
	Attempts         int               `json:"attempts"`
	MaxAttempts      int               `json:"maxAttempts"`
	NextAttemptAt    *time.Time        `json:"nextAttemptAt,omitempty"`
	DeliveredAt      *time.Time        `json:"deliveredAt,omitempty"`
	CreatedAt        time.Time         `json:"createdAt"`
	UpdatedAt        time.Time         `json:"updatedAt"`
	DeliveryAttempts []DeliveryAttempt `json:"deliveryAttempts"`
	Endpoint         *Endpoint         `json:"endpoint,omitempty"`
}

type EventConnection struct {
	Edges      []EventEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type EventEdge struct {
	Node   *Event `json:"node"`
	Cursor string `json:"cursor"`
}

type EventType struct {
	ID            string         `json:"id"`
	ClientID      string         `json:"clientId"`
	Name          string         `json:"name"`
	Description   *string        `json:"description,omitempty"`
	Schema        map[string]any `json:"schema,omitempty"`
	SchemaVersion *string        `json:"schemaVersion,omitempty"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

type EventTypeConnection struct {
	Edges      []EventTypeEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type EventTypeEdge struct {
	Node   *EventType `json:"node"`
	Cursor string     `json:"cursor"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type QueueStats struct {
	Queued     int `json:"queued"`
	Delivering int `json:"delivering"`
	Delivered  int `json:"delivered"`
	Failed     int `json:"failed"`
	Dead       int `json:"dead"`
	Pending    int `json:"pending"`
	Processing int `json:"processing"`
	Delayed    int `json:"delayed"`
}

type SendEventInput struct {
	EventType string         `json:"eventType"`
	Payload   map[string]any `json:"payload"`
	Headers   map[string]any `json:"headers,omitempty"`
}

type TestTransformationInput struct {
	Code    string        `json:"code"`
	Webhook *WebhookInput `json:"webhook"`
}

type TransformationResult struct {
	Method  string         `json:"method"`
	URL     string         `json:"url"`
	Headers map[string]any `json:"headers,omitempty"`
	Payload map[string]any `json:"payload,omitempty"`
	Cancel  bool           `json:"cancel"`
}

type TransformationTestResult struct {
	Success     bool                  `json:"success"`
	Result      *TransformationResult `json:"result,omitempty"`
	Error       *string               `json:"error,omitempty"`
	ExecutionMs int                   `json:"executionMs"`
}

type UpdateEndpointInput struct {
	URL              *string         `json:"url,omitempty"`
	Description      *string         `json:"description,omitempty"`
	EventTypes       []string        `json:"eventTypes,omitempty"`
	Status           *EndpointStatus `json:"status,omitempty"`
	Filter           map[string]any  `json:"filter,omitempty"`
	Transformation   *string         `json:"transformation,omitempty"`
	MaxRetries       *int            `json:"maxRetries,omitempty"`
	RetryBackoffMs   *int            `json:"retryBackoffMs,omitempty"`
	RetryBackoffMax  *int            `json:"retryBackoffMax,omitempty"`
	RetryBackoffMult *float64        `json:"retryBackoffMult,omitempty"`
	TimeoutMs        *int            `json:"timeoutMs,omitempty"`
	RateLimitPerSec  *int            `json:"rateLimitPerSec,omitempty"`
	CircuitThreshold *int            `json:"circuitThreshold,omitempty"`
	CircuitResetMs   *int            `json:"circuitResetMs,omitempty"`
	CustomHeaders    map[string]any  `json:"customHeaders,omitempty"`
}

type UpdateEventTypeInput struct {
	Description   *string        `json:"description,omitempty"`
	Schema        map[string]any `json:"schema,omitempty"`
	SchemaVersion *string        `json:"schemaVersion,omitempty"`
}

type WebhookInput struct {
	Method  *string        `json:"method,omitempty"`
	URL     string         `json:"url"`
	Headers map[string]any `json:"headers,omitempty"`
	Payload map[string]any `json:"payload"`
}

type EndpointStatus string

const (
	EndpointStatusActive   EndpointStatus = "ACTIVE"
	EndpointStatusPaused   EndpointStatus = "PAUSED"
	EndpointStatusDisabled EndpointStatus = "DISABLED"
)

var AllEndpointStatus = []EndpointStatus{
	EndpointStatusActive,
	EndpointStatusPaused,
	EndpointStatusDisabled,
}

func (e EndpointStatus) IsValid() bool {
	switch e {
	case EndpointStatusActive, EndpointStatusPaused, EndpointStatusDisabled:
		return true
	}
	return false
}

func (e EndpointStatus) String() string {
	return string(e)
}

func (e *EndpointStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EndpointStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EndpointStatus", str)
	}
	return nil
}

func (e EndpointStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EndpointStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EndpointStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EventStatus string

const (
	EventStatusQueued     EventStatus = "QUEUED"
	EventStatusDelivering EventStatus = "DELIVERING"
	EventStatusDelivered  EventStatus = "DELIVERED"
	EventStatusFailed     EventStatus = "FAILED"
	EventStatusDead       EventStatus = "DEAD"
)

var AllEventStatus = []EventStatus{
	EventStatusQueued,
	EventStatusDelivering,
	EventStatusDelivered,
	EventStatusFailed,
	EventStatusDead,
}

func (e EventStatus) IsValid() bool {
	switch e {
	case EventStatusQueued, EventStatusDelivering, EventStatusDelivered, EventStatusFailed, EventStatusDead:
		return true
	}
	return false
}

func (e EventStatus) String() string {
	return string(e)
}

func (e *EventStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventStatus", str)
	}
	return nil
}

func (e EventStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
